### PR TITLE
Smoothplains

### PR DESCRIPTION
**Pull request by JohnBerg60**
- plains (below level) smoothing
- redraw streams to certain depth
- tilt the map in a chosen direction
- sharpen mountains slightly

### CODE REVIEW

**Comment by JohnBerg60** [comment]
Hello,
sorry for the inconvenience. Yes, the smoothplains PR contains everything.
I was fixing some bugs, and  then some ideas came up ;)

Best,

John

PS I am working on some kind of leveling system, to make coastlines more flat, or mauntains more dramatic. Still pre alfa ..

**Comment by JohnBerg60** [comment]
Hi, i've finished a basic map leveling with 4 profiles. I"ve bin waiting with my PR for this PR to merge. Is that ok?

**Comment by sysoppl** [comment]
I will merge this today ~17:00 CET

**Comment by sysoppl** [comment]
Changes on site will be visible tomorrow

**Pull request merged**
